{% set name = "dydx-v3-python" %}
{% set version = "2.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mementorc/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: e1cae5ef5623affd7378ab3d025d93f6e4aa0ce119f184c6a8d01c978ec4e07f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8.0
    - pip
  run:
    - python >=3.8.0
    - aiohttp >=3.8.1
    - cytoolz >=0.12.1
    - dateparser >=1.0.0
    - ecdsa >=0.18.0
    - eth-keys
    - eth-account >=0.8.0
    - mpmath >=1.3.0
    - requests >=2.31.0
    - six >=1.16.0
    - sympy >=1.12.0
    - web3 >=6.5.0

test:
  imports:
    - dydx3
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/dydxprotocol/dydx-v3-python
  summary: dYdX Python REST API for Limit Orders
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MementoRC
